version: '3.8'

services:
  receita:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./settings.py:/app/settings.py
    env_file:
      - .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload